# Generated by Django 5.1.6 on 2025-03-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bank_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
