# Generated by Django 5.1.6 on 2025-03-11 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.cliente'),
        ),
    ]
