# Generated by Django 5.1.6 on 2025-03-11 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_transaction_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Client',
        ),
        migrations.AlterModelTable(
            name='client',
            table='transaction_cliente',
        ),
    ]
