# Generated by Django 5.1.6 on 2025-05-22 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_transaction_type'),
        ('transaction', '0006_clienteimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.user'),
            preserve_default=False,
        ),
    ]
